apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-ssh
  labels:
    app: dev-pod-ssh
spec:
  containers:
  - name: dev
    image: python:3.11-slim
    command: ["/bin/bash"]
    args: 
    - "-c"
    - |
      apt-get update && \
      apt-get install -y openssh-server sudo vim git && \
      mkdir -p /var/run/sshd && \
      echo 'root:devpass' | chpasswd && \
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      /usr/sbin/sshd -D
    ports:
    - containerPort: 22
      name: ssh
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
